name: Run Python Script and Commit Changes

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

permissions:
  contents: write  # Allows the action to commit changes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run scrape script
      run: python scrapeFixtures.py

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

    - name: Run aggregation script
      run: python importAndAnalyse.py

    - name: Run script to append CSV to Google Sheets
      run: |
        echo "${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}"  > google_sheets_credentials.json
        python push_to_sheets.py "${{ secrets.SHEET_ID }}" "SundayFixtures"
      env:
        CSV_FILE: "output.csv"
